server:
 port: 8083
 context-path: /case
httpServer:
  interfaceServer: "http://localhost:8082/inter/"
spring:
  datasource:
    url: jdbc:mysql://192.168.1.51:3306/platform?useUnicode=true&amp;characterEncoding=utf-8
#    url: jdbc:mysql://127.0.0.1:3306/platform?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  task:
    pool:
     corePoolSize: 10
     maxPoolSize: 20
     keepAliveSeconds: 120
     queueCapacity: 10
     
      